/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as ModulesScoutRouteImport } from './routes/modules.scout'
import { Route as ModulesScoutIndexRouteImport } from './routes/modules.scout.index'
import { Route as ModulesScoutSettingsRouteImport } from './routes/modules.scout.settings'
import { Route as ModulesScoutProspectsProspectIdRouteImport } from './routes/modules.scout.prospects.$prospectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesScoutRoute = ModulesScoutRouteImport.update({
  id: '/modules/scout',
  path: '/modules/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesScoutIndexRoute = ModulesScoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesScoutRoute,
} as any)
const ModulesScoutSettingsRoute = ModulesScoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ModulesScoutRoute,
} as any)
const ModulesScoutProspectsProspectIdRoute =
  ModulesScoutProspectsProspectIdRouteImport.update({
    id: '/prospects/$prospectId',
    path: '/prospects/$prospectId',
    getParentRoute: () => ModulesScoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/scout': typeof ModulesScoutRouteWithChildren
  '/modules/scout/settings': typeof ModulesScoutSettingsRoute
  '/modules/scout/': typeof ModulesScoutIndexRoute
  '/modules/scout/prospects/$prospectId': typeof ModulesScoutProspectsProspectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/scout/settings': typeof ModulesScoutSettingsRoute
  '/modules/scout': typeof ModulesScoutIndexRoute
  '/modules/scout/prospects/$prospectId': typeof ModulesScoutProspectsProspectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/scout': typeof ModulesScoutRouteWithChildren
  '/modules/scout/settings': typeof ModulesScoutSettingsRoute
  '/modules/scout/': typeof ModulesScoutIndexRoute
  '/modules/scout/prospects/$prospectId': typeof ModulesScoutProspectsProspectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/modules/$slug'
    | '/modules/scout'
    | '/modules/scout/settings'
    | '/modules/scout/'
    | '/modules/scout/prospects/$prospectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/modules/$slug'
    | '/modules/scout/settings'
    | '/modules/scout'
    | '/modules/scout/prospects/$prospectId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/modules/$slug'
    | '/modules/scout'
    | '/modules/scout/settings'
    | '/modules/scout/'
    | '/modules/scout/prospects/$prospectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ModulesSlugRoute: typeof ModulesSlugRoute
  ModulesScoutRoute: typeof ModulesScoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/scout': {
      id: '/modules/scout'
      path: '/modules/scout'
      fullPath: '/modules/scout'
      preLoaderRoute: typeof ModulesScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/scout/': {
      id: '/modules/scout/'
      path: '/'
      fullPath: '/modules/scout/'
      preLoaderRoute: typeof ModulesScoutIndexRouteImport
      parentRoute: typeof ModulesScoutRoute
    }
    '/modules/scout/settings': {
      id: '/modules/scout/settings'
      path: '/settings'
      fullPath: '/modules/scout/settings'
      preLoaderRoute: typeof ModulesScoutSettingsRouteImport
      parentRoute: typeof ModulesScoutRoute
    }
    '/modules/scout/prospects/$prospectId': {
      id: '/modules/scout/prospects/$prospectId'
      path: '/prospects/$prospectId'
      fullPath: '/modules/scout/prospects/$prospectId'
      preLoaderRoute: typeof ModulesScoutProspectsProspectIdRouteImport
      parentRoute: typeof ModulesScoutRoute
    }
  }
}

interface ModulesScoutRouteChildren {
  ModulesScoutSettingsRoute: typeof ModulesScoutSettingsRoute
  ModulesScoutIndexRoute: typeof ModulesScoutIndexRoute
  ModulesScoutProspectsProspectIdRoute: typeof ModulesScoutProspectsProspectIdRoute
}

const ModulesScoutRouteChildren: ModulesScoutRouteChildren = {
  ModulesScoutSettingsRoute: ModulesScoutSettingsRoute,
  ModulesScoutIndexRoute: ModulesScoutIndexRoute,
  ModulesScoutProspectsProspectIdRoute: ModulesScoutProspectsProspectIdRoute,
}

const ModulesScoutRouteWithChildren = ModulesScoutRoute._addFileChildren(
  ModulesScoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ModulesSlugRoute: ModulesSlugRoute,
  ModulesScoutRoute: ModulesScoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
