// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
// The workspace signs in through the Trust Tai client, which persists the
// session under its own storage key. Read the token from that same client or
// the header is never attached.
import { supabase } from '@/integrations/trust-tai/supabase'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
